# Generated by Django 2.1 on 2018-08-24 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagofacilFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('export_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Salesforce_file',
            new_name='SalesforceFile',
        ),
        migrations.RenameField(
            model_name='salesforcefile',
            old_name='frecuency',
            new_name='frequency',
        ),
    ]
