# Generated by Django 2.1 on 2018-08-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_auto_20180824_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofacilfile',
            name='data',
            field=models.CharField(default='', max_length=128),
        ),
    ]
