# Generated by Django 2.1 on 2018-08-26 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_pagofacilfile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofacilfile',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesforcefile',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
