# Generated by Django 2.1 on 2018-08-26 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importer', '0004_auto_20180826_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('export_date', models.DateTimeField(blank=True, null=True)),
                ('campaing_id', models.CharField(default='', max_length=10)),
                ('campaing_code', models.CharField(default='', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='salesforcefile',
            old_name='Tratamiento',
            new_name='process',
        ),
        migrations.RemoveField(
            model_name='salesforcefile',
            name='campaign',
        ),
        migrations.AddField(
            model_name='pagofacilfile',
            name='file_line',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagofacilfile',
            name='file_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesforcefile',
            name='campaign_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagofacilfile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesforcefile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
