# Generated by Django 2.1 on 2018-08-26 15:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importer', '0006_auto_20180826_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaings',
            new_name='Campaing',
        ),
    ]
