# Generated by Django 2.1 on 2018-08-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0008_auto_20180826_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagofacilfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesforcefile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
