# Generated by Django 2.1 on 2018-08-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0009_auto_20180826_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaing',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pagofacilfile',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='salesforcefile',
            old_name='author',
            new_name='user',
        ),
    ]
