# Generated by Django 2.1 on 2018-08-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0010_auto_20180826_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pagofacilfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salesforcefile',
            name='user',
        ),
    ]
