# Generated by Django 2.1 on 2018-08-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0012_sf_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforcefile',
            name='order_nro',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='salesforcefile',
            name='terminal_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
