# Generated by Django 2.1 on 2019-04-01 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0014_salesforcefile_identificated'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaing',
            name='loyalty_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaing',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valida desde'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaing',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valida desde'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaing',
            name='campaing_code',
            field=models.CharField(default='', max_length=50, verbose_name='Codigo Salesforce'),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='campaing_id',
            field=models.CharField(default='', max_length=10, verbose_name='Codigo en campaña'),
        ),
        migrations.AlterField(
            model_name='sf_ids',
            name='partner_id',
            field=models.CharField(max_length=10, verbose_name='DNI o Nro de Socio'),
        ),
        migrations.AlterField(
            model_name='sf_ids',
            name='sf_partner_id',
            field=models.CharField(max_length=100, verbose_name='ID SalesForces -15 digitos-'),
        ),
    ]
