# Generated by Django 2.1 on 2019-04-01 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0015_auto_20190401_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaing',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='Descripcion campaña'),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='loyalty_card',
            field=models.BooleanField(default=False, verbose_name='Usa credencial'),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Valida hasta'),
        ),
        migrations.AlterField(
            model_name='pagofacilfile',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pagofacilfile',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pagofacilfile',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='salesforcefile',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='salesforcefile',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='salesforcefile',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='sf_ids',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='sf_ids',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sf_ids',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
