# Generated by Django 2.1 on 2019-04-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0016_auto_20190401_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforcefile',
            name='campaign_description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
