# Generated by Django 2.1 on 2019-04-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0017_salesforcefile_campaign_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaing',
            name='valid_from',
            field=models.DateField(verbose_name='Valida desde'),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='valid_to',
            field=models.DateField(verbose_name='Valida hasta'),
        ),
    ]
