# Generated by Django 2.1 on 2019-04-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0019_auto_20190412_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaing',
            name='valid_from',
            field=models.DateField(verbose_name='Valida desde'),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='valid_to',
            field=models.DateField(verbose_name='Valida hasta'),
        ),
    ]
